#define PICO_AUDIO_SCA_PIN 9
#define PICO_AUDIO_SCL_PIN 10

#define ROTARY_SWITCH_A_PIN 13
#define ROTARY_SWITCH_B_PIN 14
#define ROTARY_SWITCH_PIN 15

#define SCREEN_SCL_PIN 16
#define SCREEN_SCA_PIN 17

#define ADC_MUX_S3_PIN 18
#define ADC_MUX_S2_PIN 19
#define ADC_MUX_S1_PIN 20
#define ADC_MUX_S0_PIN 21

#define ADC_MUX_SIGNAL_PIN 26